### PR TITLE
update to use catkin_virtualenv

### PR DESCRIPTION
**Pull request by k-okada**
As I commented on https://github.com/pyros-dev/catkin_pip/issues/109#issuecomment-367290971, chanier_virtualenv seems better in terms of our requirement

### CODE REVIEW

**Comment by k-okada** [comment]
@yuyu2172 
BTW, when we run
```
>> bloom-generate rosdebian --os-name ubuntu --os-version xenial --ros-distro kinetic
>> MAKEFLAGS= fakeroot debian/rules binary
```
we had 
```
dh_shlibdeps -l/home/k-okada/catkin_ws/ws_chainer_ros/src/catkin_pip_chainercv/debian/ros-kinetic-chainercv//opt/ros/kinetic/lib/
	dpkg-shlibdeps -Tdebian/ros-kinetic-chainercv.substvars -l/home/k-okada/catkin_ws/ws_chainer_ros/src/catkin_pip_chainercv/debian/ros-kinetic-chainercv//opt/ros/kinetic/lib/ debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python2.7/site-packages/chainercv/utils/bbox/_nms_gpu_post.so debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python2.7/site-packages/chainercv/utils/bbox/_nms_gpu_post.cpython-36m-x86_64-linux-gnu.so debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/bin/python2
dpkg-shlibdeps: error: couldn't find library libpython3.6m.so.1.0 needed by debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python2.7/site-packages/chainercv/utils/bbox/_nms_gpu_post.cpython-36m-x86_64-linux-gnu.so (ELF format: 'elf64-x86-64'; RPATH: '/home/leus/miniconda2/envs/general3/lib')
dpkg-shlibdeps: error: cannot continue due to the error above
```
Are you depends on python3?

**Comment by yuyu2172** [comment]
Hi. Sorry for late reply. 
ChainerCV should not depend on Python 3.
From the error message you gave me, it seems that you installed ChainerCV using Python3.
There is a binary file in ChainerCV (`_nms_gpu_post.cpython-***.so`) that gets compiled at installation for the particular version of Python used at that time.
I think you need to reinstall ChainerCV while making sure that you use Python2.

**Comment by k-okada** [comment]
No, I think you have setup pip module with python3
```
k-okada@p51s:/tmp$ wget
https://pypi.python.org/packages/6d/c1/ff40e5642f37fe15d1d987d3fa5834ac8f0630b1540ad74d4dac05708273/chainercv-0.8.0.tar.gz
--2018-03-16 16:49:28--
https://pypi.python.org/packages/6d/c1/ff40e5642f37fe15d1d987d3fa5834ac8f0630b1540ad74d4dac05708273/chainercv-0.8.0.tar.gz
Resolving pypi.python.org (pypi.python.org)... 151.101.72.223,
2a04:4e42:11::223
Connecting to pypi.python.org (pypi.python.org)|151.101.72.223|:443...
connected.
HTTP request sent, awaiting response... 200 OK
Length: 271038 (265K) [binary/octet-stream]
Saving to: ‘chainercv-0.8.0.tar.gz’

chainercv-0.8.0.tar 100%[===================>] 264.69K  --.-KB/s    in
0.01s

2018-03-16 16:49:28 (23.7 MB/s) - ‘chainercv-0.8.0.tar.gz’ saved
[271038/271038]

k-okada@p51s:/tmp$ tar -tvzf chainercv-0.8.0.tar.gz  | grep cpyt
-rwxrwxr-x leus/leus    175949 2017-10-16 18:05
chainercv-0.8.0/chainercv/utils/bbox/_
nms_gpu_post.cpython-36m-x86_64-linux-gnu.so
```

Does this cpython-32m file is necessary in pip module? if not, can you
remove this?

BTW, Chanier CV does not work on Python3?  catkin_virtualenv can support
both python2 and python3 , but if we change to python3, we still have error
on building debs.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 7dfa708..5d32d00 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -8,8 +8,8 @@ find_package(catkin REQUIRED catkin_virtualenv)
 catkin_package()


 # Generate the virtualenv, optionally with python 3 as the default
interpreter:
-catkin_generate_virtualenv()
-# catkin_generate_virtualenv(PYTHON3)
+# catkin_generate_virtualenv()
+catkin_generate_virtualenv(PYTHON3)
```

```
bloom-generate rosdebian --os-name ubuntu --os-version xenial --ros-distro
kinetic
MAKEFLAGS= fakeroot debian/rules binary
```

```
Requirement already satisfied: six>=1.9.0 in
/home/k-okada/.local/lib/python3.5/site-packages (from
chainer>=3.2->chainercv>=0.8->-r
/home/k-okada/catkin_ws/ws_chainer_ros/src/catkin_pip_chainercv/obj-x86_64-linux-gnu/generated_requirements.txt
(line 2))
Requirement already satisfied: setuptools in
./venv/lib/python3.5/site-packages (from
protobuf>=3.0.0->chainer>=3.2->chainercv>=0.8->-r
/home/k-okada/catkin_ws/ws_chainer_ros/src/catkin_pip_chainercv/obj-x86_64-linux-gnu/generated_requirements.txt
(line 2))
Building wheels for collected packages: rospkg, chainercv, PyYAML, chainer,
filelock
  Running setup.py bdist_wheel for rospkg ... done
  Stored in directory:
/home/k-okada/.cache/pip/wheels/ff/ca/21/931bc2010baa0efdea1a133403dd7b7a33818919d5de9b8163
  Running setup.py bdist_wheel for chainercv ... error
  Failed building wheel for chainercv
  Running setup.py clean for chainercv
  Running setup.py bdist_wheel for PyYAML ... done

```

```
dh_shlibdeps
-l/home/k-okada/catkin_ws/ws_chainer_ros/src/catkin_pip_chainercv/debian/ros-kinetic-chainercv//opt/ros/kinetic/lib/
dpkg-shlibdeps -Tdebian/ros-kinetic-chainercv.substvars
-l/home/k-okada/catkin_ws/ws_chainer_ros/src/catkin_pip_chainercv/debian/ros-kinetic-chainercv//opt/ros/kinetic/lib/
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/fft/
fftpack_lite.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/random/
mtrand.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/
multiarray.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/
multiarray_tests.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/
struct_ufunc_test.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/
operand_flag_tests.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/
umath.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/
umath_tests.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/
test_rational.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/_
dummy.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/.libs/libgfortran-ed201abd.so.3.0.0
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/.libs/
libopenblasp-r0-39a31c03.2.18.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/linalg/
lapack_lite.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/linalg/_
umath_linalg.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/chainercv/utils/bbox/_nms_gpu_post.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/chainercv/utils/bbox/_
nms_gpu_post.cpython-36m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/chainercv/utils/bbox/_
nms_gpu_post.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/google/protobuf/internal/_
api_implementation.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/google/protobuf/pyext/_
message.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/bin/python3
dpkg-shlibdeps: error: couldn't find library libgfortran-ed201abd.so.3.0.0
needed by
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/.libs/
libopenblasp-r0-39a31c03.2.18.so (ELF format: 'elf64-x86-64'; RPATH: '')
dpkg-shlibdeps: error: couldn't find library libpython3.6m.so.1.0 needed by
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/chainercv/utils/bbox/_
nms_gpu_post.cpython-36m-x86_64-linux-gnu.so (ELF format: 'elf64-x86-64';
RPATH: '/home/leus/miniconda2/envs/general3/lib')
dpkg-shlibdeps: error: cannot continue due to the errors listed above
Note: libraries are not searched in other binary packages that do not have
any shlibs or symbols file.
To help dpkg-shlibdeps find private libraries, you might need to use -l.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/ros-kinetic-chainercv.substvars
-l/home/k-okada/catkin_ws/ws_chainer_ros/src/catkin_pip_chainercv/debian/ros-kinetic-chainercv//opt/ros/kinetic/lib/
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/fft/
fftpack_lite.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/random/
mtrand.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/
multiarray.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/
multiarray_tests.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/
struct_ufunc_test.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/
operand_flag_tests.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/
umath.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/
umath_tests.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/
test_rational.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/core/_
dummy.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/.libs/libgfortran-ed201abd.so.3.0.0
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/.libs/
libopenblasp-r0-39a31c03.2.18.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/linalg/
lapack_lite.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/numpy/linalg/_
umath_linalg.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/chainercv/utils/bbox/_nms_gpu_post.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/chainercv/utils/bbox/_
nms_gpu_post.cpython-36m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/chainercv/utils/bbox/_
nms_gpu_post.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/google/protobuf/internal/_
api_implementation.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/lib/python3.5/site-packages/google/protobuf/pyext/_
message.cpython-35m-x86_64-linux-gnu.so
debian/ros-kinetic-chainercv/opt/ros/kinetic/share/chainercv/venv/bin/python3
returned exit code 2
debian/rules:50: recipe for target 'override_dh_shlibdeps' failed
```

--
◉ Kei Okada


2018-03-16 14:31 GMT+09:00 Yusuke Niitani <notifications@github.com>:

**Comment by yuyu2172** [comment]
Oh, yes. Files distributed on PyPi contains files compiled with Python3.6.

 This is a known issue that is planned to be solved in the next release. Currently, the master branch of ChainerCV is unstable due to new features, and we can not release the new version now. Sorry for inconvenience.

I checked the error message you wrote. I think the error is caused because the minor versions of your environment and the one used to compile PyPi files are different (yours=3.5, pypi=3.6).
This problem can hopefully be resolved by removing the version dependent files.

**Comment by k-okada** [comment]
ok i have  build deb file by removing `36m-x86_64-linux-gnu.so` file.
https://drive.google.com/file/d/17Sp7lO29Zdk5AilTZM1jNe7lIEBs2qYh/view?usp=sharing

can you `dpkg -i` this file and check if working? I concerned that we do not deliver pip directory within deb, but need to run pip during dpkg install phase.

**Comment by knorth55** [comment]
I tested on my local machine and works fine.

**Pull request merged**
